### ISSUE TITLE
Additional geode buds should be harvestable with silk touch

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/WorldOfPannotia-MC-Modpack#193]
We have modified the loot table for vanilla amethyst buds to allow harvesting with silk touch. We should do the same for the other geode types.

Edit:
After looking at the loot tables for Spectrum, I discovered that their budding crystals can be harvested with a Spectrum enchantment called Resonance. My new plan is to use this in place of Silk Touch for the HT version of the pack. So all budding crystals except for those from AE2 will be harvestable with Resonance, not Silk Touch. This includes the vanilla budding amethyst block.

**Comment by moshner** [comment]
You might not need that. AE2 has the spacial storage cells that can pick up any block even spawners without silk touch. At least you don't need it for the certus quartz blocks. They can be improved and moving the flawless is part of the progression of the pack.

**Comment by chimericdream** [comment]
Are you suggesting that instead of making the other budding blocks harvestable, we remove that from the amethyst blocks in favor of using AE2?

**Comment by moshner** [comment]
Not necessarily. For the HT version of the pack we shouldn't need to make certus quartz minable with silk touch, there are already mechanics in place. 

If we removed the silk touch option for budding amethyst it would hurt the non HT version of the pack too much. 

For the other geode buds: we should probably make the harvestable with silk touch since most people won't be using AE2.

**Comment by chimericdream** [comment]
I wouldn't remove it from the non-HT version. I was thinking about making all of the non-AE2 buds harvestable with silk touch, then adding a 10-20% chance for the AE2 ones to keep their level instead of degrading when you break them. Alternatively, I could just add silk touch to the non-AE2 geodes and call it a day...

**Comment by chimericdream** [comment]
Added in beta.1
