### ISSUE TITLE
Make Orb of Origins craftable

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/WorldOfPannotia-MC-Modpack#195]
**Mod:** Origins
**Output:** `origins:orb_of_origin`
**Input(s):** ??
**Shape:** 

x . a . x
a . x . a
x . b . x

_a_: item a
_b_: item b
_x_: empty

**Comment by moshner** [comment]
suggestions: 
item a: nether stars
item b: player head

**Comment by chimericdream** [comment]
Added in beta.1
