### ISSUE TITLE
Superflat world won't render

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#198]
**Pack Version:** 1.19.2-13.0.0-ht-beta.0
**Mod Name:** n/a

**Describe the bug**
When creating a superflat world it instead renders a normal world with normal terrain

**Expected behavior**
A superflat world for my test builds

**Comment by chimericdream** [comment]
It seems that this is a known issue with Terralith, and the only current solution is to disable the mod entirely before starting the game.
