### ISSUE TITLE
Unbreaking IV Not Possible

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#200]
If I combine Unbreaking III and Unbreaking III in the anvil I get Unbreaking III :(

**Comment by moshner** [comment]
I tried you fix during lunch and combining Fortune III books doesn't give me Fortune IV

**Comment by chimericdream** [comment]
Leaving this open in the hopes that the No Enchant Cap mod may be able to add a fix, but this is an unfortunate compatibility issue between Goblin Traders and No Enchant Cap.
