### ISSUE TITLE
charcoal dust to coal dust

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#204]
**Type:** Industrial Centrifuge
**Mod:** Tech Reborn
**Output:**  tech_reborn:coal_dust
**Input(s):** tech_reborn:charcoal_dust
**Shape:** n/a
**Time:** 5 sec

In the same way that dark ashes can be purified into ashes in the centrifuge but more appropriate for early game conversions

**Comment by chimericdream** [comment]
Added in dev
