### ISSUE TITLE
Hopper X-Treme hoppers don't pull from Danks

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#206]
I had a dank in dock a on a diamond hopper and it wouldn't pull anything out. A regular hopper works.

**Comment by chimericdream** [comment]
This is a known issue with my hopper mod. The Fabric docs aren't very clear about this, but you have to explicitly implement the Item Transfer API. I basically need to rewrite Hopper X-Treme, so...

**Comment by moshner** [comment]
FWIW Copper pipes don't work either.

**Comment by chimericdream** [comment]
I can't know for 100% certain, but I'd be willing to bet it's for the exact same reason. Fabric's documentation for mod developers is pretty good for the most part, but there are some fairly significant things like this that could be presented quite a bit better.
