### ISSUE TITLE
Omnitool is destroyed when right clicking a bontany pot

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#209]
**Pack Version:** world-of-pannotia--1.19.2-13.1.0-ht.zip

**Mod Name:** Botany Pot/Tech Reborn

**Describe the bug**
If I right click on a botany pot to get into the configuration menu with my omnitool from tech reborn it makes a path block out of the dirt and the omni tool disappears forever

**Expected behavior**
Opens the botany pot but my tool stays

**Comment by chimericdream** [comment]
It looks like this is a known issue with Botany Pots:

https://github.com/Darkhax-Minecraft/BotanyPots/issues/301

**Comment by chimericdream** [comment]
Fixed in 13.2.0
