### ISSUE TITLE
Allow Batpacks on back

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#210]
**Pack Version:** 13.3.0-HT
**Mod Name:** Tech Reborn & Better Batpacks

**Description**
Add the ability to put the batpacks on a backpack slot in curios.

**Comment by chimericdream** [comment]
I'm not sure why, but it looks like they explicitly _removed_ support for this in Tech Reborn when updating to 1.19.

https://github.com/TechReborn/TechReborn/commit/9683023658cb4e0a1b6b132085ce5cca10190593
