### ISSUE TITLE
Dye-able Botany Pots

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#212]
**Type:** crafting
**Mod:** Botany Pots
**Output:** botany/hopper botany pot of the new color but the same tier
**Input(s):** any botany pot or hopper botany pot of any tier + any dye
**Shape:** shapeless

**Comment by moshner** [comment]
FYI, There is a suggestion into the mod to add this. It was opened November 2022 though. https://github.com/Darkhax-Minecraft/BotanyPots/issues/110

**Comment by chimericdream** [comment]
I may hold off on this for now in the hopes that it will be added to the actual mod. Doing this via datapack (the only option if done within the context of a modpack) would require adding 15 shapeless recipes for each pot. Between regular pots, hopper pots, and all the tiered versions, there are ~140 (if my mental math is right) different pots. So this alone would be over 2000 JSON files.

It's a good idea, and my first instinct was to add the "planned" label, but for the reason above I think it's best to wait at least a little bit.

**Comment by chimericdream** [comment]
Added in dev
