### ISSUE TITLE
Farmer's Delight Rice doesn't work in botany pot

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#213]
**Pack Version:** 13.3.0-ht
**Mod Name:** Botany Pots

**Describe the bug**
Rice should be a valid crop with water but it isn't allowing me to place it in water. Not sure if pack bug or mod bug.

**To Reproduce**
1. Put down botany pot
2. Add a bucket of water to the bottom slot
3. Try to add a farmersdesight:rice to the top slot
4. Doesn't add to the pot

**Expected behavior**
Adds the item to the pot and makes more rice

**Additional context**
https://github.com/Darkhax-Minecraft/BotanyPots/blob/45dac0b24eafa3eb446cbae66ea7ab12cbc881d4/Common/src/main/resources/data/botanypots/recipes/farmersdelight/crop/rice.json

**Comment by chimericdream** [comment]
Can you reproduce this with just FD and BP, or does it happen specifically in our pack?

**Comment by moshner** [comment]
No

**Comment by chimericdream** [comment]
I was able to reproduce this with only Botany Pots and Farmer's Delight. Looking through both mods' GitHub issues, it seems like they have had this problem in the past. It was supposedly fixed, but it might be worth bringing it up with them again.

**Comment by moshner** [comment]
I've posted a bug: https://github.com/Darkhax-Minecraft/BotanyPots/issues/317
