### ISSUE TITLE
Sky stone

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#215]
**Type:** Crafting
**Mod:** AE2 & Tech Reborn
**Output:** ae2:sky_stone_block
**Input(s):** uu-matter and obsidian
**Shape:** diagram

x . x . x
x . a . x
x . b . x

_a_: uu-matter
_b_: obsidian
_x_: empty

**Comment by chimericdream** [comment]
Added in dev
