### ISSUE TITLE
Mermaids Brush

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#216]
**Type:** Crafting (Ideally in the pigment crafter but if you cannot do that then the regular crafting table)
**Mod:** If the crafting mechanic is provided by a mod (e.g. "washing" from Create), list it here
**Output:** specrum:mermaids_brush
**Input(s):** specrum:light_blue_sapling, water, specrum:four_leaf_clover
**Shape:** diagram

x . a . x
a . c . a
x . b . x

_a_: four leaf clover
_b_: water bucket
_c_: Light Blue Sapling
_x_: empty

**Comment by chimericdream** [comment]
Added in dev
