### ISSUE TITLE
Quitoxic Reeds

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#217]
**Type:** Crafting, prefereably through spectrum altar
**Mod:** Specrum
**Output:** spectrum:quitoxic_reeds
**Input(s):** Purple Pigment, minecraft:sugar_cane
**Shape:** diagram

a . b . a
a . b . a
a . b . a

_a_: sugar cane
_b_: purple pigment

**Comment by chimericdream** [comment]
Added in dev
