### ISSUE TITLE
Budding blocks in botany pots

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#218]
In the same way that coral blocks, fans, etc. can be grown in botany pots, what if we could grow crystals?

**Type:** Botany Pots
**Mod:** Botany Pots
**Output:** Crystals
**Input(s):** Budding block + fully grown crystal
**Shape:** Shapeless

Possible recipes:
1. Certus Quartz (AE2)
2. Amethyst (Minecraft)
3. Quartz (More Geodes)
4. Emerald (More Geodes)
5. Echo Shards (More Geodes?)
6. Onyx (Spectrum)
7. Citrine (Spectrum)
8. that other one (Spectrum)
9. etc.

**Comment by chimericdream** [comment]
Added in dev
