### ISSUE TITLE
Mermaids Gems in Botany Pots

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#219]
**Type:** Botany Pots
**Mod:** Spectrum + Botany Pots
**Output:** Mermaid's Gem
**Input(s):** Water + Mermaid's Comb

Since this item doesn't use up any other material or requires other things like time of day, I suggest that we can make it pot-able.

**Comment by chimericdream** [comment]
Added in dev
