### ISSUE TITLE
Quitoxic Botany Pot

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#220]
**Type:** Botany Pot
**Mod:** Spectrum + Botany Pot + Minekea
**Output:** Quitoxic
**Input(s):** Quitoxic + 5x Compressed Clay

Because the Quitoxic plan usually uses up the clay to grow I suggest requiring a heavy clay tax by making it require at least a 4x compressed clay to grow. Maybe more?

**Comment by chimericdream** [comment]
Added in dev
