### ISSUE TITLE
Spectrum Loot Table Generation is Broken

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#221]
**Pack Version:** 13.5.0-HT
**Mod Name:** Spectrum

**Describe the bug**
All the loot chests in Spectrum are defaulting to the "Dike" version of the ancient ruin so we cannot get any of the advanced materials. 

More information in this tread on the Spectrum discord:

https://discord.com/channels/906264467636109333/923661883452588053/1103750389767078061

**Comment by moshner** [comment]
This is probably because of some mod/data-pack interaction

**Comment by chimericdream** [comment]
Fixed in dev
