### ISSUE TITLE
Blood Orchid Botany Pot

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#222]
**Type:** Botany Pot
**Mod:** Spectrum and Botany Pots
**Output:** 5 Blood Orchid Petals
**Input(s):** Blood Orchid Plant and any dirt

The blood orchid is a flower type that only drops petals that you can 'pick' up to 5 in any growing session. I don't recommend being able to dup the flower itself because there are special crafting recipes to do that.

**Comment by chimericdream** [comment]
Added in dev
