### ISSUE TITLE
Water isn't infinite anymore

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#41]
I pull water from a 2x2 pool and it doesn't settle anymore.

**Comment by chimericdream** [comment]
Fix coming in 2.1.2. Here's the change to make locally since it could take a few hours for the updated pack to be available in the launcher:

In `overrides\config\infinitefluids.cfg`, remove the comma after `minecraft:water` on line 17.

**Comment by chimericdream** [comment]
Fix submitted to Curse. I'll close this once it's available in the launcher.
