### ISSUE TITLE
Ctrl+Click to decompress all compressed dirt

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#42]
When I Ctrl+Click to decompress all compressed dirt in a stack it only gives me 9 dirt. This happened after the update to 2.1.

**Comment by chimericdream** [comment]
I just tested 2.0.1 and 2.1.1, and they both have the same functionality. Ctrl+Click decompresses one at a time, and Shift+Click decompresses the whole stack.

**Comment by moshner** [comment]
added locally
