### ISSUE TITLE
Emerald Shedding Not Working

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#47]
I've had 4 villagers in my base since before the change #35 was pushed and I don't have a single emerald from them. I think something is wrong.

**Comment by chimericdream** [comment]
I'll take a look. If I don't get to it before you, can you set up a copy of your villager farm but with spiders? I want to see if all shedding is broken or just villagers. If the latter, it's possible Botania changed something since 1.7.10.

**Comment by chimericdream** [comment]
I just confirmed this. Apparently, just turning shedding on isn't enough. Once shedding is enabled, a whole new set of configs generates, and that's where you configure shedding on a per-mob basis.

**Comment by moshner** [comment]
Shedding is working on a local game with 2.2.0
