### ISSUE TITLE
Tinkers (specifically, the TAIGA add-on) crashing MC

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#49]
I thought I would re-open a ticket related to this so that I can post my issues.

**Comment by moshner** [comment]
I just had a crash with my cleaver. 
Cleaver:
![2017-02-19_15 31 12](https://cloud.githubusercontent.com/assets/3300206/23106800/86f49ad4-f6b8-11e6-86d6-eb8951232840.png)
Crash Report:
[crash-2017-02-19_15.27.25-client.txt](https://github.com/chimericdream/WorldOfPannotia-MC-Modpack/files/786225/crash-2017-02-19_15.27.25-client.txt)

**Comment by chimericdream** [comment]
I submitted a PR to Tinker's Construct that should fix this. It isn't released yet, but should be in the next one.

**Comment by chimericdream** [comment]
@moshner with regard to the crashes you were getting killing creepers and stuff with your ranged weapons, does this issue match your situation?

https://github.com/TeamFRM/TAIGA/issues/130

**Comment by moshner** [comment]
I'm not sure it matches but I'm not an expert at reading logs.

True, the game crashed when I killed a creeper but it crashed with weapons
from three different mod packs.

Nick Mosher | Designer
http://nick.mosher.me

**Comment by chimericdream** [comment]
Ok. Specifically, I wasn't sure if your weapons had the same trait as his, but I forgot that you weren't just using Tinker's weapons.
