### ISSUE TITLE
Tin won't work in compacting drawers

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#50]
I place a block of tin into the compacting drawer and it doesn't show the ingots or nugget (?) versions. Using version 2.2.1

**Comment by chimericdream** [comment]
I don't know why, but you need to place the ingots first. Could be a bug in storage drawers.

**Comment by moshner** [comment]
I don't care about this one anymore. I've got enough AE storage to spare.

**Comment by chimericdream** [comment]
Okie dokie.
