### ISSUE TITLE
Metamorph Crashing the Server

### ISSUE THREAD

**Issue by moshner** [chimericdream/WorldOfPannotia-MC-Modpack#54]
1) Killing a creeper with the flair chakrum.
2) This time killing a creeper again using a tinkers crossbow.
3) This time killing a creeper using a wyvern bow from Draconic Evolution. Strangely enough I had just killed another creeper with that same bow from that same place without a problem.

Neither time I was morphed.

**Comment by chimericdream** [comment]
@moshner I haven't noticed this since 2.2.2. As far as you can tell, is this fixed?

**Comment by moshner** [comment]
I haven't dared to try anything that was crashing the server since 2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.22.2.2.2.2.2.2.2.2.2.2......

I can try to fly around and shoot things with things until it crashes or I get all the loot next time I'm in.

**Comment by chimericdream** [comment]
Fixed
