### ISSUE TITLE
[Mod] HydroGel

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/WorldOfPannotia-MC-Modpack#59]
https://minecraft.curseforge.com/projects/hydrogel

This just adds a solid block that acts as a water source for farms. It's a minor annoyance, but I routinely find myself falling into the water blocks in the sugar cane farm when collecting drops.

**Comment by moshner** [comment]
lol

**Comment by moshner** [comment]
You can't just place a block over the water?
