### ISSUE TITLE
Set up wiki

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/WorldOfPannotia-MC-Modpack#6]

**Comment by moshner** [comment]
This would be helpful. Especially helpful to link to the mod's websites that are in the pack.

**Comment by chimericdream** [comment]
@moshner What should the wiki contain, besides links to the mod websites/Curse pages/wikis? Install instructions?

I was thinking maybe include the links to mod sites/whatever in the main readme, and then use the wiki to group them. For example, IC2 and the mods that add more content to it; ambiance mods like Mo' Creatures, Biomes O' Plenty, etc; AE2; Tinker's; etc.

I want it to be useful, but I also am not sure what would be most useful.

**Comment by moshner** [comment]
Really the most useful thing would be to see all the custom changes we have made.
