### ISSUE TITLE
Additional Bars mod

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/WorldOfPannotia-MC-Modpack#88]
Link: https://www.curseforge.com/minecraft/mc-mods/additional-bars

This mod adds different variants of bars, including horizontal bars (floor grates, anyone?) and crossed bars (I'm thinking jails).

![wooden_bars(1)](https://user-images.githubusercontent.com/198075/87479449-21053100-c5f1-11ea-81d4-372e14e1df72.png)

![crossed-vanilla-bars](https://user-images.githubusercontent.com/198075/87479417-1185e800-c5f1-11ea-9f63-36e4e9e1b662.png)

![2020-07-03_23](https://user-images.githubusercontent.com/198075/87479424-1480d880-c5f1-11ea-9bed-0199576669e3.png)

**Comment by moshner** [comment]
+1

**Comment by chimericdream** [comment]
Added in 8.0-rc.1
