### ISSUE TITLE
Craftable clay

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/WorldOfPannotia-MC-Modpack#92]
It would be really nice if clay could be crafted from something else. Possibly 8 gravel around a bucket of water yields 8 clay balls?

**Comment by moshner** [comment]
What if we made it possible to get clay out of terracotta instead?

**Comment by chimericdream** [comment]
That could work. Perhaps the same recipe, but terracotta instead of gravel? The main reason I was thinking of using gravel is that with a cobble gen + Immersive Engineering, gravel is renewable. So that route would make clay renewable as well, which is what I'm running into as I try to craft all the colors of terracotta for an "all things colorful" store.

**Comment by moshner** [comment]
That could work. Terracotta is renewable with villager trading after all.
We could also add clay to the villager trades.

Nick Mosher | Designer
http://nick.mosher.me

**Comment by moshner** [comment]
What if we took inspiration from one of these DIY home recipes? https://www.wikihow.com/Make-Clay

1. One option: Water, salt, and flour. 
2. Another would be 'clay rich soil' and water. That one could be like a clay duper... 1 water bucket, 2 clay ball, 6 dirt makes 9 clay balls?

**Comment by chimericdream** [comment]
Ooh, I like those. I could even see it as coarse dirt -> clay blocks, since coarse dirt is craftable from 2 dirt and 2 gravel. Maybe if you use regular dirt, you get clay balls, and coarse dirt nets clay blocks?

**Comment by moshner** [comment]
That would work.

**Comment by chimericdream** [comment]
Added in 8.0-rc.1
