### ISSUE TITLE
Spawner tweaks

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/WorldOfPannotia-MC-Modpack#97]
[Enhanced Mob Spawners](https://www.curseforge.com/minecraft/mc-mods/enhanced-mob-spawners)

The mod we have that enables silk touching mob spawners has other configs that we may not want. I left most of the default ones in place for the latest beta, but after some testing think that we should disable some.

Current configs:
* Monsters drop eggs: 0.1%
  * By default, the mod set this to a 4% chance for a monster to drop its egg when you kill it. I changed it to 0.1% but think 1% might be better. 4% seemed high to me.
* Remove egg from spawner: enabled
  * Does what it says on the tin. This lets you right click any spawner to get the mob egg from it. ~~I think we should disable this.~~ _It turns out if you disable this, then silk touching the spawner is kind of useless. When you place spawners you silk touched, they start out empty._
* Silk touch spawners: enabled
  * I think we should leave this enabled
* Change spawn rate, speed, distance: enabled
  * The mod allows you to tweak basically all parts of a mob spawner. I'm not sure how I feel about this, ~~but think we should turn it off~~.

**Comment by moshner** [comment]
I agree with all of the changes

**Comment by chimericdream** [comment]
Done in rc.0
